/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deadwood_gui;

import javax.swing.JOptionPane;

/**
 *
 * @author bans
 */
public class DeadWood_GUI extends javax.swing.JFrame {
    private static DeadWood_GUI gui;

    /**
     * Creates new form GUI
     */
    public DeadWood_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        controllerPanel = new javax.swing.JPanel();
        playerLabel = new javax.swing.JLabel();
        moveButton = new javax.swing.JButton();
        actionButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        boardPane = new javax.swing.JLayeredPane();
        boardLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        playerLabel.setText("It is player ____'s turn:");

        moveButton.setText("Move");

        actionButton.setText("Action");

        javax.swing.GroupLayout controllerPanelLayout = new javax.swing.GroupLayout(controllerPanel);
        controllerPanel.setLayout(controllerPanelLayout);
        controllerPanelLayout.setHorizontalGroup(
            controllerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controllerPanelLayout.createSequentialGroup()
                .addComponent(playerLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(controllerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moveButton)
                .addGap(274, 274, 274)
                .addComponent(actionButton)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        controllerPanelLayout.setVerticalGroup(
            controllerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controllerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(controllerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moveButton)
                    .addComponent(actionButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        boardPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/board.jpg"))); // NOI18N
        boardPane.add(boardLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jScrollPane1.setViewportView(boardPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(controllerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(controllerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Shows a dialog which prompts the user for an integer. Will keep showing the dialog until a valid integer is entered.
     * @param prompt the message to show to the user
     * @param suggested the initial value in the input box
     * @return the integer entered by the user
     */
    public int getInteger(String prompt,int suggested)
    {
        String s;
        do
        {
            s = JOptionPane.showInputDialog(this, prompt, suggested + "");
        } while (!DeadWood.isInteger(s));
        return Integer.parseInt(s);
    }
    
    /**
     * Adds a new visual element to the board by creating a new JLabel in the board pane and setting its position.
     * Must be called whenever a new element is first drawn to the board. Afterward, use {@link #moveBoardElement}
     * to update its position or {@link destroyBoardElement} to remove an element.
     * @param imgPath the file path of the image to use for this element
     * @param x starting x coordinate
     * @param y starting y coordinate
     * @return a unique integer identifier for this element - used to reference this element in subsequent method calls
     */
    public int addBoardElement(String imgPath, int x, int y)
    {
        // TODO
        return 0;
    }
    
    /**
     * Updates the position of the board element referred to by {@code identifier}.
     * Board elements must first be created by calling {@link addBoardElement}.
     * @param identifier id of element to move
     * @param newx new x coordinate
     * @param newy new y coordinate
     */
    public void moveBoardElement(int identifier, int newx, int newy)
    {
        // TODO
    }
    
    /**
     * Removes the board element referred to by {@code identifier} from the board pane.
     * Used when a previously created board element should no longer be drawn.
     * @param identifier id of element to destroy
     */
    public void destroyBoardElement(int identifier)
    {
        // TODO
    }
    
    /**
     * @return a newly created GUI object
     */
    public static DeadWood_GUI get() {
        if(gui != null) return gui;
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeadWood_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeadWood_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeadWood_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeadWood_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        DeadWood_GUI gui = new DeadWood_GUI();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                gui.setVisible(true);
            }
        });
        return gui;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actionButton;
    private javax.swing.JLabel boardLabel;
    private javax.swing.JLayeredPane boardPane;
    private javax.swing.JPanel controllerPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton moveButton;
    private javax.swing.JLabel playerLabel;
    // End of variables declaration//GEN-END:variables
}
